name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Copy files to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/MyProjectsPortfolio/hello-devops
            git pull origin main
            docker build -t hello-devops .
            docker stop hello-devops || true
            docker rm hello-devops || true
            docker run -d --name hello-devops -p 80:80 hello-devops

